### ISSUE TITLE
Imagens dos botões.

### ISSUE THREAD

**Issue by emanoelantonio** [Hwooh/Insta-DIO#1]
Olá Eduardo! Antes de mais nada estou aprendendo igual você, e é comum errar coisas bobas. Então fica tranquilo quanto a isso!
Bom, dando uma olhada no seu **CSS** o caso dos **BOTÕES**:

`.app-download: nth-child(1) {
    background-image: url('apple-button.png');
}

.app-download: nth-child(2) {
    background-image: url('googleplay-button.png');
}`
**do modo como está, não indica o caminho onde as imagens se encontram**. **Dá uma olhada no meu:**

`.app-download:nth-child(1) {
    background-image: url('./img/app-store-botao.png');
}

.app-download:nth-child(2) {
    background-image: url('./img/google-play-botao.png');
}`
**nota que eu coloquei as imagens numa pasta e indiquei o caminho.** 
**Ah, só não esquece de subir a pasta para o github.**

**Comment by Hwooh** [comment]
Opa Emanoel! obrigado por responder! 

O problema persiste mesmo eu indicando o caminho.

**Comment by emanoelantonio** [comment]
Você poderia subir a pasta com as imagens para eu testar aqui? Te mando um fork corrigido.

**Comment by Hwooh** [comment]
Subi a pasta

**Comment by emanoelantonio** [comment]
Ok, vou fazer as modificações e vc confere.

**Comment by Hwooh** [comment]
Ok! Obrigado novamente por ajudar

**Comment by emanoelantonio** [comment]
Olá novamente Eduardo! Como prometido, fiz as alterações pra você conferir e se lhe atendeu pode aplicar.

**Comment by Hwooh** [comment]
Boa tarde Emanoel! Eu vi suas alterações e finalmente percebi meu erro! Eu estava colocando as imagens soltas na pasta em que o HTML e CSS estão, precisei criar uma pasta dentro dessa pasta para guardar somente as imagens. Aparentemente as imagens que eu indicava através do HTML funcionavam normalmente sem elas estarem em uma pasta separada, porém as 2 imagens que eu indicava através do CSS não funcionavam. Agora na pasta separada tudo funcionando direitinho. Muito obrigado pela ajuda!!!

**Comment by emanoelantonio** [comment]
Disponha sempre que precisar! Costumo dizer que nós Devs somos como motoqueiros, sempre se ajudando. Pois bem, agora você pode fechar a issue.
